// Versioning from Conventional Commits.
//
// Reads the commits since the last `v*` tag, picks the bump
//   BREAKING CHANGE / `type!:`  -> major
//   feat                        -> minor
//   anything else               -> patch
// then writes the new version to package.json, prepends a section to
// CHANGELOG.md and writes RELEASE_NOTES.md (the GitHub release body).
//
//   node scripts/release.mjs            apply
//   node scripts/release.mjs --dry-run  print what would happen
//   node scripts/release.mjs minor      force a level
//
// In GitHub Actions it also sets the `version` step output.

import { execSync } from "node:child_process";
import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const forced = args.find((a) => ["major", "minor", "patch"].includes(a));

const sh = (cmd) => {
  try {
    return execSync(cmd, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
};

const prevTag = sh("git describe --tags --abbrev=0 --match 'v*'");
const range = prevTag ? `${prevTag}..HEAD` : "HEAD";
const SEP = "\u001f";
const commits = sh(`git log ${range} --no-merges --pretty=format:%s${SEP}%b${SEP}%h%x1e`)
  .split("\u001e")
  .map((c) => c.trim())
  .filter(Boolean)
  .map((c) => {
    const [subject, body = "", hash = ""] = c.split(SEP);
    const m = subject.match(/^(\w+)(?:\(([^)]+)\))?(!)?:\s*(.+)$/);
    return {
      type: m ? m[1].toLowerCase() : "other",
      scope: m?.[2],
      breaking: Boolean(m?.[3]) || /BREAKING[ -]CHANGE/.test(body),
      text: m ? m[4] : subject,
      hash: hash.trim(),
    };
  })
  .filter((c) => !/^chore\(release\)/.test(`${c.type}(${c.scope})`) && !/\[skip ci\]/.test(c.text));

if (commits.length === 0 && !forced) {
  console.log("No commits since", prevTag || "the start", "— nothing to release.");
  process.exit(0);
}

const level =
  forced ?? (commits.some((c) => c.breaking) ? "major" : commits.some((c) => c.type === "feat") ? "minor" : "patch");

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const [major, minor, patch] = pkg.version.split(".").map(Number);
const version =
  level === "major" ? `${major + 1}.0.0` : level === "minor" ? `${major}.${minor + 1}.0` : `${major}.${minor}.${patch + 1}`;

const GROUPS = [
  ["⚠️ Breaking changes", (c) => c.breaking],
  ["✨ Features", (c) => c.type === "feat"],
  ["🐛 Bug fixes", (c) => c.type === "fix"],
  ["⚡ Performance", (c) => c.type === "perf"],
  ["📝 Documentation", (c) => c.type === "docs"],
  ["🔧 Other changes", () => true],
];
const used = new Set();
let notes = "";
for (const [title, match] of GROUPS) {
  const items = commits.filter((c) => !used.has(c) && match(c));
  if (!items.length) continue;
  items.forEach((c) => used.add(c));
  notes += `### ${title}\n\n${items.map((c) => `- ${c.scope ? `**${c.scope}:** ` : ""}${c.text}${c.hash ? ` (${c.hash})` : ""}`).join("\n")}\n\n`;
}
notes ||= "- Maintenance release.\n\n";

const now = new Date();
const date = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
const section = `## v${version} — ${date}\n\n${notes}`;

if (dryRun) {
  console.log(`${pkg.version} -> ${version} (${level})\n\n${section}`);
  process.exit(0);
}

pkg.version = version;
writeFileSync("package.json", `${JSON.stringify(pkg, null, 2)}\n`);

const header = "# Changelog\n\nAll notable changes to this project. Generated by `scripts/release.mjs`.\n\n";
const old = existsSync("CHANGELOG.md") ? readFileSync("CHANGELOG.md", "utf8").replace(/^# Changelog[\s\S]*?(?=## |$)/, "") : "";
writeFileSync("CHANGELOG.md", `${header}${section}${old}`);
writeFileSync("RELEASE_NOTES.md", notes);

if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, `version=${version}\n`);
console.log(`Released v${version} (${level})`);
